### ISSUE TITLE
Should be deleted: MVACARTGiniTree1 has almost the same code

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-1708-MVACARTBan2#2]

**Comment by polarstern** [comment]
So what should we do with this gitlet?

**Comment by lborke** [comment]
I will examine that and give an answer A.S.A.P...

**Comment by lborke** [comment]
This Q does another tree classification with other paramteres. And it is used in the MVA book.
Plz complete the validation and let me know when ready to be moved to READY ;-)
